<a href="https://colab.research.google.com/github/vrao1/SHALA-2020/blob/master/Assignment_1_DS.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>


# **Assignment - 1 : Getting Started**

---

This assignment will get you familiarized with python libraries required for ***data science*** and ***machine learning***. You will have to complete the code snippets and run them. 

## **Note :**   Use only the methods and attributes of the ```numpy``` library. **Do not** hard-code them. Avoid loops as much as possible.

---
## Part - 1
 In this part, you will work with the library ```numpy```. 




Import ```numpy``` with an alias name ```np```. Initialize two arrays $a$, $b$ of size $3 \times 5$ with random values and print them. 

In [25]:
import numpy as np
a = np.random.randint(100, size=(3,5))
b = np.random.randint(100, size=(3,5))
print(a)

print(b)

[[42 84 75 68  6]
 [68 47  3 76 52]
 [78 15 20 99 58]]
[[23 79 13 85 48]
 [49 69 41 35 64]
 [95 69 94  0 50]]


Initialize and print two arrays $c$ and $d$ having the following properties:
*   $c$ is a row vector with all non-negative integer values less than 100
* $d$ is a square matrix of size 3 having all entries as 0.0

In [26]:
c = np.random.randint(100, size=(100))

print(c)

d = np.zeros((3,3))

print(d)

[36 34 48 93  3 98 42 77 21 73  0 10 43 58 23 59  2 98 62 35 94 67 82 46
 99 20 81 50 27 14 41 58 65 36 10 86 43 11  2 51 80 32 54  0 38 19 46 42
 56 60 77 30 24  2  3 94 98 13 40 72 19 95 72 26 66 52 67 61 14 96  4 67
 11 86 77 75 56 16 24 29 21 25 80 60 61 83 33 32 70 85 31 13 71 56 24 79
 41 18 40 54]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


We have $e$ as following : ```e = [[1,2,3],[4,5,6],[7,8,9]]```. Change $e$ as a numpy array and print it.

In [27]:
e = [[1,2,3],[4,5,6],[7,8,9]]
f = np.array(e)
print(f)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


$f$ and $g$ are two square matrices of size 5 such that all the entries of $f$ are 1 and $g$ is an identity matrix. Initialize them and print them

In [28]:
f = np.ones((5,5), dtype=int)
g = np.identity(5, dtype=int)
print(f)

print(g)

[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]
[[1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]]


Reshape $c$ into a $10 \times 10$ matrix and name it $h$. Now flatten $h$, call it $c^\prime$ and print **YES** when the shapes of $c$ and $c^\prime$ are same. Otherwise print **NO**.

In [29]:
h = c.reshape((10,10))

print(h)

c_prime = h.flatten()

if c.shape == c_prime.shape:
  print("YES")
else:
  print("NO")

[[36 34 48 93  3 98 42 77 21 73]
 [ 0 10 43 58 23 59  2 98 62 35]
 [94 67 82 46 99 20 81 50 27 14]
 [41 58 65 36 10 86 43 11  2 51]
 [80 32 54  0 38 19 46 42 56 60]
 [77 30 24  2  3 94 98 13 40 72]
 [19 95 72 26 66 52 67 61 14 96]
 [ 4 67 11 86 77 75 56 16 24 29]
 [21 25 80 60 61 83 33 32 70 85]
 [31 13 71 56 24 79 41 18 40 54]]
YES


Let $A$ denote a randomly initialized three dimensional matrix of shape (2,10,5). Transpose $A$, call it $A^\prime$, such that its shape is (5,2,10) and print it.

In [30]:
A = np.random.rand(2,10,5)
print(A)

#A_prime = 
#print(np.transpose(A, (5,2,10)))

#print(A_prime)

[[[1.02863359e-01 9.23738895e-02 3.54046662e-01 5.51816259e-01
   3.36250935e-02]
  [9.68961765e-01 3.20997241e-01 2.21262685e-01 1.41263905e-01
   9.72599271e-02]
  [9.84042241e-01 2.60340928e-01 5.37022521e-01 4.47926172e-01
   9.95690891e-02]
  [3.52311661e-01 4.69249174e-01 8.41140130e-01 9.04647744e-01
   3.75593838e-02]
  [5.08315449e-01 1.66847513e-01 7.79051020e-01 8.64933296e-01
   4.11396724e-01]
  [1.39972585e-01 3.32223853e-02 9.82574960e-01 3.73290751e-01
   4.20075370e-01]
  [5.05881151e-02 3.65496106e-01 1.66279737e-02 2.30742335e-01
   7.64911699e-01]
  [9.44123519e-01 7.49999249e-01 3.39403819e-01 4.89548937e-01
   3.38985117e-01]
  [1.79490261e-01 1.70986599e-01 4.63450977e-01 8.74572958e-01
   9.44119751e-01]
  [6.08252866e-01 5.96655406e-01 7.83644245e-01 5.00026298e-01
   5.03700568e-02]]

 [[6.99098075e-01 9.92396399e-01 2.67262538e-01 6.79090616e-01
   8.64281443e-01]
  [7.50844246e-01 9.64489768e-01 5.54242435e-01 2.12390499e-01
   2.22443224e-01]
  [2.18749374e

You have a matrix $X$ of size (10,5) filled with random values. Print the following :
* Minimum value and index where it occured, for each column
* Maximum value and the index where it occured, for each column
* Minimum value and index where it occured, for each row
* Maximum value and index where it occured, for each row
* Minimum value and index where it occured, for the entire matrix
* Maximum value and index where it occured, for the entire matrix

In [31]:
np.random.seed(0)
X = np.random.rand(10,5)
mi = np.min(X, axis=0)
print(mi)

ma = np.max(X, axis=0)
print(ma)

mi_r = np.min(X, axis=1)
print(mi_r)

ma_r = np.max(X, axis=1)
print(ma_r)

mi_all = np.min(X)
print(mi_all)

ma_all = np.max(X)
print(ma_all)

[0.0871293  0.0202184  0.1289263  0.06022547 0.0187898 ]
[0.97861834 0.79915856 0.94466892 0.96366276 0.87001215]
[0.4236548  0.38344152 0.07103606 0.0202184  0.11827443 0.14335329
 0.0187898  0.61209572 0.06022547 0.1289263 ]
[0.71518937 0.96366276 0.92559664 0.87001215 0.97861834 0.94466892
 0.77423369 0.94374808 0.6976312  0.67063787]
0.018789800436355142
0.978618342232764


Find and print the following for the matrix X: 
* Mean of each row and column
* Standard deviation of each row and column
* Mean of the entire matrix
* Standard deviation of entire matrix

In [21]:

column_mean = np.mean(X, axis=0)
row_mean = np.mean(X, axis=1)

column_stdev = np.std(X, axis=0)
row_stdev = np.std(X, axis=1)

mean = np.mean(X)
stdev = np.std(X)

print(column_mean)
print(row_mean)

print(column_stdev)
print(row_stdev)

print(mean)
print(stdev)

[0.56044382 0.46781457 0.62009909 0.64025127 0.40121685]
[0.56706085 0.66447172 0.57705944 0.51762729 0.62761197 0.5328907
 0.41643268 0.69444672 0.44423265 0.33781717]
[0.24687647 0.25752158 0.22948615 0.28054144 0.26584905]
[0.09445299 0.23322986 0.29189733 0.38052993 0.30431633 0.26338419
 0.25841437 0.12727959 0.23169975 0.18537332]
0.5379651182755409
0.27226582292177587


Let $Y$ denote a square matrix of size 10 with random values. Print the following:
* Determinant
* Rank of the matrix
* Diagonal Elements
* Trace
* Eigen values
* Matrices obtained after Singular Value Decomposition
* Inverse if exists, otherwise Pseudo-Inverse
* Multiplication $Y$ with $X$
* Element-wise multiplication of $Y$ and its inverse(or pseudo-inverse)

In [36]:
import numpy as np

np.random.seed(3)
Y=np.random.rand(10,10)

det=np.linalg.det(Y)
print("Determinant :", det)

rank = np.linalg.matrix_rank(Y)
print("Rank : ", rank)

diag = Y.diagonal()
print("Diagonal : ", diag)

trace = np.matrix.trace(Y)
print("Trace : ", trace)

eig = np.linalg.eigvals(Y)
print("Eiegenvalues : ", eig)

SyntaxError: ignored

## End of Part - 1
 --- --- ---

## Part - 2
---
In this part, you will be working with the library ```pandas```. Import this library with an alias name ```pd```.

In [0]:
# Initial imports
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

Download dataset from: http://biostat.mc.vanderbilt.edu/wiki/pub/Main/DataSets/titanic3.csv
Read the data and display the first 5 rows

In [24]:
#Download dataset from: http://biostat.mc.vanderbilt.edu/wiki/pub/Main/DataSets/titanic3.csv

file_url = "http://biostat.mc.vanderbilt.edu/wiki/pub/Main/DataSets/titanic3.csv"

df = pd.read_csv(file_url)
df.head()

SyntaxError: ignored

### Preprocessing of the Dataset



---


**1. Convert the categorical values of columns 'sex', 'embarked', 'pclass' into dummy values and add them into titanic_data_new DataFrame**




---



In [0]:
titanic_data_new = pd.get_dummies(df, columns=['sex', 'embarked', 'pclass'])
titanic_data_new.head()



---


**2. Fill the missing data in Age and Fare columns with the mean value of the respected column then add these columns to titanic_data_new**


---



In [0]:
titanic_data_new['age_w'] = titanic_data_new['age'].fillna(titanic_data_new['age'].mean())
titanic_data_new['fare_w'] = titanic_data_new['fare'].fillna(titanic_data_new['fare'].mean())
print(titanic_data_new.head())

###Normalization


---



1. Normalize the columns which have numerical data



---



In [37]:
x = df[['age']].values.astype(float)
min_max_scaler = preprocessing.MinMaxScaler()
x_scaled = min_max_scaler.fit_transform(x)
df_normalized = pd.DataFrame(x_scaled)

x = df[['fare']].values.astype(float)
min_max_scaler = preprocessing.MinMaxScaler()
x_scaled = min_max_scaler.fit_transform(x)
df_normalized_fare = pd.DataFrame(x_scaled)

print(df_normalized)
print(df_normalized_fare)

NameError: ignored



---
2. Drop the original age, fare columns
3. Append the normalized columns to the titanic_data_new DataFrame.



---



In [0]:
df.drop(columns=['age', 'fare'], inplace=True)
df.head()

titanic_data_new['age_norm'] = df_normalized
titanic_data_new['age_fare'] = df_normalized_fare

###Plotting
1. plot the age against the ID(continuous)
2. plot the fare against the ID(scatter)

In [0]:
import matplotlib.pyplot as plt
plt.plot(x=df['age'], y=df['id'])
plt.xlabel('Age')
plt.ylabel('ID')
plt.show()

plt.scatter(x=df['fare'], y=df['id'])
plt.xlabel('Fare')
plt.ylabel('ID')
plt.show()

## End of Part - 2
---

## Part - 3
---

In this part, you will work with the library ```matplotlib```. Import the ```pyplot``` from ```matplotlib``` with an alias name ```plt```.

In [0]:
import matplotlib.pyplot as plt
import math

Plot the sine function with domain in $[-3\pi,3\pi]$. Label the axes appropriately. Add title $\sin(x)$. Use latex formatting while adding the title. Set the plot size to (10,10)

In [0]:
x=np.arange(-3*math.pi , 3*math.pi, 0.1)
plt.plot(X=x, Y=math.sin)
plt.xlabel('SIN')
plt.ylabel('Values')
plt.show()

Plot $\sin(x)$ and its spectrum, $\cos(x)$ and its spectrum in a single plot, in the domain $[-2\pi,2\pi]$. Label the plot appropriately.

In [0]:
x=np.arange(-2*math.pi , 2*math.pi, 0.1)

plt.figure(figsize=(9, 3))

plt.subplot(131)
plt.plot(x, math.sin(x))
plt.subplot(132)
plt.scatter(x, math.cos(x))
plt.suptitle('Sin Cos Plotting')
plt.show()

## End of Part - 3
---

Create a Github repository with the name ***SHALA2020*** and save this assignment there.