<a href="https://colab.research.google.com/github/vrao1/SHALA-2020/blob/master/Assignment_1_DS.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>


# **Assignment - 1 : Getting Started**

---

This assignment will get you familiarized with python libraries required for ***data science*** and ***machine learning***. You will have to complete the code snippets and run them. 

## **Note :**   Use only the methods and attributes of the ```numpy``` library. **Do not** hard-code them. Avoid loops as much as possible.

---
## Part - 1
 In this part, you will work with the library ```numpy```. 




Import ```numpy``` with an alias name ```np```. Initialize two arrays $a$, $b$ of size $3 \times 5$ with random values and print them. 

In [2]:
import numpy as np
a = np.random.randint(100, size=(3,5))
b = np.random.randint(100, size=(3,5))
print(a)

print(b)

[[ 3 77 62 95 12]
 [36 55 87 64 24]
 [75 81  8 45 37]]
[[45 43 85 17 47]
 [ 5 82 46 14  7]
 [50 73  9 50 90]]


Initialize and print two arrays $c$ and $d$ having the following properties:
*   $c$ is a row vector with all non-negative integer values less than 100
* $d$ is a square matrix of size 3 having all entries as 0.0

In [3]:
c = np.random.randint(100, size=(100))

print(c)

d = np.zeros((3,3))

print(d)

[54 50 90 54 15  2  7 96 58 53 77 59 90 88 82 93 33 68 19 42 65 88 41 57
 19 77 83 18 75 97  2 68 19 62 87 87 48 55 97 20 31 22 27 37 13 49 50 30
 10  8 51 18 37 16 57 28 39  4 75 15 25 46 71  0 93 82 38 42 76 30 24 51
 11 88 58 38 29 46 13 12 98 50 35 45 41 98 48 71 79 98  2  8 12 77 53 43
  0 85 66 90]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


We have $e$ as following : ```e = [[1,2,3],[4,5,6],[7,8,9]]```. Change $e$ as a numpy array and print it.

In [4]:
e = [[1,2,3],[4,5,6],[7,8,9]]
f = np.array(e)
print(f)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


$f$ and $g$ are two square matrices of size 5 such that all the entries of $f$ are 1 and $g$ is an identity matrix. Initialize them and print them

In [5]:
f = np.ones((5,5), dtype=int)
g = np.identity(5, dtype=int)
print(f)

print(g)

[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]
[[1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]]


Reshape $c$ into a $10 \times 10$ matrix and name it $h$. Now flatten $h$, call it $c^\prime$ and print **YES** when the shapes of $c$ and $c^\prime$ are same. Otherwise print **NO**.

In [6]:
h = c.reshape((10,10))

print(h)

c_prime = h.flatten()

if c.shape == c_prime.shape:
  print("YES")
else:
  print("NO")

[[54 50 90 54 15  2  7 96 58 53]
 [77 59 90 88 82 93 33 68 19 42]
 [65 88 41 57 19 77 83 18 75 97]
 [ 2 68 19 62 87 87 48 55 97 20]
 [31 22 27 37 13 49 50 30 10  8]
 [51 18 37 16 57 28 39  4 75 15]
 [25 46 71  0 93 82 38 42 76 30]
 [24 51 11 88 58 38 29 46 13 12]
 [98 50 35 45 41 98 48 71 79 98]
 [ 2  8 12 77 53 43  0 85 66 90]]
YES


Let $A$ denote a randomly initialized three dimensional matrix of shape (2,10,5). Transpose $A$, call it $A^\prime$, such that its shape is (5,2,10) and print it.

In [8]:
A = np.random.rand(2,10,5)
print(A)

#A_prime = 
#print(np.transpose(A, (5,2,10)))

#print(A_prime)

[[[0.28679586 0.47544628 0.73095089 0.73230678 0.2230743 ]
  [0.04125706 0.35851403 0.75620785 0.49410424 0.0754174 ]
  [0.721653   0.12804055 0.69025915 0.37016822 0.60638994]
  [0.8070614  0.07476142 0.23302211 0.67325762 0.42121423]
  [0.00817524 0.59324237 0.03638224 0.67545206 0.57846315]
  [0.51641416 0.86580292 0.62737282 0.28138177 0.57674826]
  [0.25334448 0.64019524 0.58808127 0.98218852 0.53147083]
  [0.60993115 0.22594303 0.38196151 0.12056331 0.8279238 ]
  [0.79764238 0.79989231 0.45699276 0.12804331 0.27903668]
  [0.49690042 0.21215867 0.03662321 0.87101386 0.13969865]]

 [[0.45062142 0.67816027 0.7628934  0.09790332 0.23085063]
  [0.92385415 0.65468808 0.15737922 0.87917437 0.49563884]
  [0.32544449 0.79531769 0.20830775 0.70158869 0.54591718]
  [0.76863212 0.74325288 0.02670166 0.54050493 0.15469838]
  [0.48924892 0.65716878 0.28231193 0.70323978 0.39039335]
  [0.36368847 0.95435383 0.64798064 0.68726621 0.96794892]
  [0.43741763 0.1103692  0.01799115 0.87403791 0.21035

You have a matrix $X$ of size (10,5) filled with random values. Print the following :
* Minimum value and index where it occured, for each column
* Maximum value and the index where it occured, for each column
* Minimum value and index where it occured, for each row
* Maximum value and index where it occured, for each row
* Minimum value and index where it occured, for the entire matrix
* Maximum value and index where it occured, for the entire matrix

In [9]:
np.random.seed(0)
X = np.random.rand(10,5)
mi = np.min(X, axis=0)
print(mi)

ma = np.max(X, axis=0)
print(ma)

mi_r = np.min(X, axis=1)
print(mi_r)

ma_r = np.max(X, axis=1)
print(ma_r)

mi_all = np.min(X)
print(mi_all)

ma_all = np.max(X)
print(ma_all)

[0.0871293  0.0202184  0.1289263  0.06022547 0.0187898 ]
[0.97861834 0.79915856 0.94466892 0.96366276 0.87001215]
[0.4236548  0.38344152 0.07103606 0.0202184  0.11827443 0.14335329
 0.0187898  0.61209572 0.06022547 0.1289263 ]
[0.71518937 0.96366276 0.92559664 0.87001215 0.97861834 0.94466892
 0.77423369 0.94374808 0.6976312  0.67063787]
0.018789800436355142
0.978618342232764


Find and print the following for the matrix X: 
* Mean of each row and column
* Standard deviation of each row and column
* Mean of the entire matrix
* Standard deviation of entire matrix

In [12]:

column_mean = np.mean(X, axis=0)
row_mean = np.mean(X, axis=1)

column_stdev = np.std(X, axis=0)
row_stdev = np.std(X, axis=1)

mean = np.mean(X)
stdev = np.std(X)

print(column_mean)
print(row_mean)

print(column_stdev)
print(row_stdev)

print(mean)
print(stdev)

[0.56044382 0.46781457 0.62009909 0.64025127 0.40121685]
[0.56706085 0.66447172 0.57705944 0.51762729 0.62761197 0.5328907
 0.41643268 0.69444672 0.44423265 0.33781717]
[0.24687647 0.25752158 0.22948615 0.28054144 0.26584905]
[0.09445299 0.23322986 0.29189733 0.38052993 0.30431633 0.26338419
 0.25841437 0.12727959 0.23169975 0.18537332]
0.5379651182755409
0.27226582292177587


Let $Y$ denote a square matrix of size 10 with random values. Print the following:
* Determinant
* Rank of the matrix
* Diagonal Elements
* Trace
* Eigen values
* Matrices obtained after Singular Value Decomposition
* Inverse if exists, otherwise Pseudo-Inverse
* Multiplication $Y$ with $X$
* Element-wise multiplication of $Y$ and its inverse(or pseudo-inverse)

In [0]:
np.random.seed(3)
Y = np.random.rand(10,10)

det = np.linalg.det(Y)
rank = np.linalg.matrix_rank(Y)

print(det)
print(rank)

## End of Part - 1
 --- --- ---

## Part - 2
---
In this part, you will be working with the library ```pandas```. Import this library with an alias name ```pd```.

In [0]:
# Initial imports
import numpy as np
import matplotlib.pyplot as plt


Download dataset from: http://biostat.mc.vanderbilt.edu/wiki/pub/Main/DataSets/titanic3.csv
Read the data and display the first 5 rows

In [0]:
#Download dataset from: http://biostat.mc.vanderbilt.edu/wiki/pub/Main/DataSets/titanic3.csv

file_url = "http://biostat.mc.vanderbilt.edu/wiki/pub/Main/DataSets/titanic3.csv"



### Preprocessing of the Dataset



---


**1. Convert the categorical values of columns 'sex', 'embarked', 'pclass' into dummy values and add them into titanic_data_new DataFrame**




---





---


**2. Fill the missing data in Age and Fare columns with the mean value of the respected column then add these columns to titanic_data_new**


---



###Normalization


---



1. Normalize the columns which have numerical data



---





---
2. Drop the original age, fare columns
3. Append the normalized columns to the titanic_data_new DataFrame.



---



###Plotting
1. plot the age against the ID(continuous)
2. plot the fare against the ID(scatter)

## End of Part - 2
---

## Part - 3
---

In this part, you will work with the library ```matplotlib```. Import the ```pyplot``` from ```matplotlib``` with an alias name ```plt```.

Plot the sine function with domain in $[-3\pi,3\pi]$. Label the axes appropriately. Add title $\sin(x)$. Use latex formatting while adding the title. Set the plot size to (10,10)

Plot $\sin(x)$ and its spectrum, $\cos(x)$ and its spectrum in a single plot, in the domain $[-2\pi,2\pi]$. Label the plot appropriately.

## End of Part - 3
---

Create a Github repository with the name ***SHALA2020*** and save this assignment there.